### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MrkarlosM** [mricanho/Youtube-clone#2]
Hello there Joel, I'm starting this Issue so we can all give you feedback on your project!

**Comment by MrkarlosM** [comment]
Please, don't forget to add the "alt" attribute to all media you have on your page, also filling it with descriptive words.

Also don't forget that the correct indentation for a css file is done with two spaces, "not tab spacing".

![image](https://user-images.githubusercontent.com/33767393/96885796-8e262f00-1448-11eb-9cf7-1732038361eb.png)

**Comment by AntonyOtero** [comment]
I Think the code is coming along very well. The only thing I might suggest is not using inline styling, like on line 103 of your index.html file:

`<p>You're viewing YouTube in <strong>English (US).</strong> You can <span style="color: #267ac6;">change this preference below</span></p>`

It's good practice to use classes and style the element from your css stylesheet. Keep up the good work. 👍🏼

**Comment by abongsjoel** [comment]
Thanks for all the feedback guys, i really appreciate
